--- #YAML:1.0
name: CGI-Wiki-Kwiki
version: 0.41
license: perl
distribution_type: module
requires:
  CGI: 0
  CGI::Kwiki: 0
  CGI::Wiki: 0.05
  CGI::Wiki::Formatter::Kwiki: 0
  Getopt::Long: 0
  Search::InvertedIndex: 0
  Template: 0
  Time::Piece: 0
  perl: 5.6.0
recommends:
  CGI::Wiki::Formatter::Multiple: 0
  DBD::SQLite: 0
  DBI: 0
  Test::HTML::Content: 0
build_requires:
  Digest::MD5: 0
  Test::More: 0
conflicts: {}
provides:
  CGI::Wiki::Kwiki:
    file: lib/CGI/Wiki/Kwiki.pm
    version: 0.41
generated_by: Module::Build version 0.19
